### PR TITLE
Pyramid images

### PR DESCRIPTION
**Pull request by will-moore**
This is the #1 PR, updated with current main branch merged.

I don't know how close this is to being "ready", but I wanted to test again how recent updates to napari have improved the handling of big images, especially with the async flags described in https://napari.org/dev/guides/rendering.html

Tested with:
```
$ NAPARI_ASYNC=1 NAPARI_OCTREE=1 napari-omero
```
Haven't tried any octree configuration.

This allows big images to be viewed, and I can see that napari is only loading tiles for regions of the image that are in the viewport.
But it still feels that some tiles are getting loaded repeatedly - e.g. the lowest resolution is loaded repeatedly, even when not zoomed-out.

And after a bit of zooming and panning, I get complaints about memory usage:

Screenshot 2023-04-18 at 10 16 03

This is testing with an svs image available at https://downloads.openmicroscopy.org/images/SVS/

### CODE REVIEW

**Comment by tlambert03** [comment]
Yeah I have no reason to expect this will work any better now than it ever has... 

Large data still just mostly chokes in napari

**Comment by psobolewskiPhD** [comment]
@jo-mueller @will-moore would be interesting to revisit this.
with napari-ome-zarr, the current (new) async in napari, I can load very large pyramidal WSI ome-zarr with no issues. Very performant, at least for US east coast bucket and my US east coast location.
So for the napari side at least that use case should be doable!

**Comment by psobolewskiPhD** [comment]
I think this is working with napari 0.5.5 and NAPARI_ASYNC=1
I don't see any real issues, it behaves very well!
I think even the caching is working, which Im not sure it does with napari-ome-zarr. I have the same dataset in both GCP as ome-zarr and in OMERO.

@will-moore do you want to pick this back up? Otherwise I could pick up off this branch and get main merged in to fix the double loading and other issues, then we can see how it behaves and think about the next steps.

**Comment by will-moore** [comment]
Thanks @psobolewskiPhD. Great to hear that this is working for you.
Please feel free to grab my branch and go from there.

**Pull request closed without merging**
