### PR TITLE
windows ci fix

### PR DESCRIPTION
**Pull request by tlambert03**
trying to fix windows tests on github actions

### CODE REVIEW

**Comment by joshmoore** [comment]
Perhaps try installing pywin32? From omero-py's tox.ini:

```
    pywin32; platform_system=="Windows"
```

May need to get that pulled up into setup.py.

cc: @will-moore

**Comment by joshmoore** [comment]
Oops. Looks like this got orphaned. Good to go?

**Comment by tlambert03** [comment]
sure, it only tests on 3.8, but better than nothing

**Comment by joshmoore** [comment]
:+1: Merging and we can see where we want to go from here.

**Comment by joshmoore** [comment]
Failed on master unfortunately:

```
 ERROR tests/test_utils.py - OSError: [WinError 87] The parameter is incorrect
```

**Pull request merged**
