### PR TITLE
Python 3.8 should work

### PR DESCRIPTION
**Pull request by manics**
Python 3.8 Zeroc IcePy builds were recently added: https://anaconda.org/ome/zeroc-ice36-python/files

### CODE REVIEW

**Comment by joshmoore** [comment]
Re-launched job (3.7) which timed out.

**Comment by tlambert03** [comment]
Awesome thanks!  You’ll also need to update tox.ini to get testing on 3.8

**Comment by tlambert03** [comment]
Last question before merge, should we update the `conda create` Instructions to use python=3.8, or just leave with 3.7 as the example for now.  I generally prefer being on 3.8 unless you have any insight on that

**Comment by tlambert03** [comment]
Oh, and just for my edification... is there anything special about the zeroc ice bundle in the ome channel? Or should it conceivably work with the ice packages in conda-forge?

**Comment by manics** [comment]
The conda-forge zeroc-ice package is lacking Windows builds. I opened an issue a while back but didn't receive a response:
https://github.com/conda-forge/zeroc-ice-feedstock/issues/3

The conda-forge package would also need to provide two versions of ice, 3.6 and 3.7, since OMERO doesn't work with the latter.

Regarding Python version, officially we recommend Python 3.6 but in practice other versions seem to work. @joshmoore ?

**Comment by tlambert03** [comment]
Ahh, I see.  Looks like they do offer [v3.6](https://anaconda.org/conda-forge/zeroc-ice/files?version=3.6.5) but only on Linux.  

Relatedly, itd be nice to get this package (napari-omero) on conda, but I assume this ice limitation means it would need to go in the ome channel; right?

**Comment by manics** [comment]
Yes. Ideally all ome packages would be on conda-forge but ice is a blocker 😥.

**Comment by joshmoore** [comment]
- Think we're fairly comfortable with 3.5 through 3.7
 - Having the 3.8 Ice build should hopefully bump that up one notch
 - Happy to have this in the ome channel until conda-forge sorts Ice, or if conda-forge will allow napari-omero to be there with a dependency to the ome channel that seems simple enough

**Pull request merged**
